spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database:
      platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true